payments/mobile-pay/after-payment.md

1. Changed "sam" to "same"
2. Changed "upto" to "up to"

Fixed typo found under "Capture Sequence"

---

payments/mobile-pay/other-features.md

Under "Create payment" and before "Payment", there was a missing statement for table formatting, meaning the table did not match the visual look of the others.

Fixed table formatting

---

payments/vipps/other-features.md

We had an oopsie
Vipps referenced payment orders, so we fixed that.

Remove payment order from vipps other features

---

_includes/alert-agreement-required.md
_includes/unscheduled-purchase.md
payments/swish/after-payment.md

Did some minor textual and request changes.
The wiki request/response has both authorization and autocapture as intent. I wanted to add authorization only, since we aren't supposed tu encourage use of AutoCapture, but I wanted to keep it in until talking to Kristiansen tomorrow.
Perhaps a flow chart would be nice as well?

Minor fixes

---

resources/release-notes.md

* New page! Technical reference into has been moved from the front page
to [technical information][home-technical-information].
* Front page got a slimmer look. :swimmer:
* Abort reference is back in credit card reference.
* Swish error code reference got a face lift, check out
swish api errors :candy:.

Release 1.7.5 (develop)

---

resources/release-notes.md

* Updated [Invoice Payments Direct][invoice-direct] where
`approvedLegalAddress` should now be use for all countries.
* Small text changes and clarifications.
* Restructured [Invoice Payments][invoice] and [Card Payments][card].

Release 1.8.0

---

resources/release-notes.md

* Documented allowed characters in `orderItem.class`.
* Added `receiptReference` in Invoice Payments and
Payment Order in capture and reversal.
* Callback is now moved to Other features in all payments intruments.
* Clean up of MobilePay.
* Corrected the address of Leia Ahlström in Test Data.
* Updated the documentation in Card Payments
to recommend using `shippingAddress`.
* Updated `payeeReference` to have an unique description for Payment Order and
every Payment Instrument.

Release 1.8.1 (develop)

---

.github/workflows/deploy.yml
.github/workflows/rebase.yml
.github/workflows/verify_build_output.yml
_config.yml
docker-compose.yml
index.md

Removes the `livereload.js` script by upgrading to version 1.5 of the theme and version 1.3.8 of `jekyll-plantuml`. Also upgrades the Design Guide to version 4.6.1 for good measure.

DX-980: Remove livereload

---

payments/card/direct.md

fra Havard Glattre:  Jeg skjønner direct integrasjonen bare skal funke for 3ds1 inntil videre, og det betyr at densannsynligvis ikke kommer til å få nye integrasjoner. Inntil videre ser det ut som den vil forsvinne når 3ds1 forsvinner. Dermed gjør vi den så korrekt som mulig nå for eksisterende integratører som har den.

dx-1007 correct Card direct diagram

---

_includes/one-click-payments.md

In the table below the code example it says this parameter is called "noCvc" which is also what I use in my implementation.

Updated documentation mismatch regarding "noCvc"

---

docker-compose.yml

Upgrade jekyll-plantuml to version 2.0.4 to get SwedbankPay/jekyll-plantuml-docker#34 that pass auth token from environment variable to HTMLProofer to avoid GitHub responding with `429 Too Many Requests`.

DX-1064: Authenticate HTMLProofer requests

---

resources/release-notes.md

Version 1.12.1
*   Corrected the documentation by removing `generatePaymentToken` and
`paymentToken` from Checkout.

Release 1.12.1(develop) 

---

resources/release-notes.md

Version 1.13.3
*   Added documentation on deprecated operations in Checkout..
*   Updated `instrument` description in Checkout.
*   Updated `payeeReference` description.
*   Clarified `msisdn` and `shoplogoUrl` in MobilePay Payments.
*   Updated Test data in Resources.
*   Documented problems in Trustly Payments.
*   Added an alert for two-phase payments in Capture pages.

Release 1.13.3 (develop)

---

_includes/payment-resource.md

We are going to fix in production so that Trustly does not show a `view-sales` operation but a `view-sale` (note sale in singular) operation instead. I will "undraft" this PR once we are in prod with the change.

ESF-972 view-sale operation should be singular, not plural

---

modules-sdks/index.md

Add back the `redirect_from` front matter directive that was nuked in ea6db6ca4804a2ff7cfea623b06fea52901951df.

DX-1199: Add back redirect_from to Modules & SDKs

---

_includes/field-description-amount.md

Tried to make it a bit more general. Used "transaction" instead of payment, as the payment consists of one or more transactions. This way we are including the reversals and cancellations as well.

DX-1309 Text in amount include

---

checkout/checkin.md

ESM-1311 Changes now reflect the new flow on initiate-consumer-session. shippingAddressRestrictedToCountryCodes should not be required when requireShippingAddres is set to false.

ESM-1311 Upate Checkin with new flow

---

docker-compose.yml

Bump jekyll-plantuml from version 2.1.1 to 2.1.4 for SwedbankPay/jekyll-plantuml-docker#91 so we get the Git branch injected into the Jekyll build process, hopefully producing URLs that don't lead to `404` on internal pull requests.

DX-1446: Bump jekyll-plantuml from version 2.1.1 to 2.1.4

---

modules-sdks/mobile-sdk/android.md
modules-sdks/mobile-sdk/ios.md

Instead refer to distribution pages that should always reflect the latest releases.

Remove references to particular versions of the mobile SDK components

---

Gemfile.lock

Bump theme from v1.9.10 to v1.9.13 to [anonymize IP addresses in Google Analytics](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization).

DX-1507: Bump theme from v1.9.10 to v1.9.13 to anonymize IP addresses in GA (master)

---

Gemfile.lock

Bump theme from v1.9.12 to v1.9.13 to [anonymize IP addresses in Google Analytics](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization).

DX-1507: Bump theme from v1.9.12 to v1.9.13 to anonymize IP addresses in GA (develop

---

.github/release-drafter.yml

Adds a `dependencies` section to the release and removes the explicit increment of `patch` as `patch` is incremented by default.

DX-969: Adjust release drafter configuration

---

.github/scripts/variables.sh
.github/workflows/release-pr.yml

Add GitHub Actions workflow that creates two pull requests (one for `develop` and one for `master`) when a `release/*` branch is pushed.

DX-969: Add workflow for PR creation on release branch push

---

_includes/payment-order-abort.md
_includes/payment-order-get.md
_includes/update-payment-order.md

Removed the settings node from all the payment order responses I could find.

DX-1545: Remove settings node from payment order responses

---

.github/mergify.yml
.github/release-drafter.yml
.github/workflows/release-pr.yml
_config.yml

Tweaks the release process a bit.
- The GitHub Action that creates pull requests for releases now only creates PR on the first `push` of the release branch. Subsequent pushes to the release branch should not incur new pull requests.
- Stop Mergify from thanking bots for their contributions.
- Reorder the headers in the description of releases so "Documentation" is placed on the top and "Dependencies" at the bottom.
- Searchyll should no longer index documents in production since [it is failing](https://github.com/SwedbankPay/developer.swedbankpay.com/runs/3241034364#step:3:215).

Searchyll release fixes (master)

---

modules-sdks/mobile-sdk/android.md
modules-sdks/mobile-sdk/plain-webview.md

Change Android SDK documentation to mention Maven Central rather than Bintray, which no longer contains up-to-date versions of the SDK.
Also updated the "Plain WebView" section with Android 11 changes.

Update Android documentation

---

.github/mergify.yml

Switching to queue action due to strict mode deprecation ref https://blog.mergify.com/strict-mode-deprecation/

DX-1653 Switch to queue action

---

_includes/enterprise-payer-reference.md

Removed the code example and hyperlinked them back to the payment order requests instead.

DX-1721: Re-do MAC payerReference

---

resources/release-notes.md

*   Added descriptive card icons
*   Added Payer Aware Payment Menu
*   Added new screenshots for Checkout v3 implementations
*   Rewrote instrument mode section
*   Reorganized features in the sidebar
*   Fixed internal links

Release notes for 3.0.1 (develop)

---

payment-instruments/swish/redirect.md

Removed "paymenturl" in swish redirect.

DX-1705 Remove PaymentUrl from Swish

---

.github/workflows/azure-production.yml
.github/workflows/azure-stage.yml

The deploy workflow is not able to upload the files due to an update for Azure cli ([az storage blob upload-batch returns ErrorCode:BlobAlreadyExists error v2.34.0 on upload · Issue #21477 · Azure/azure-cli](https://github.com/Azure/azure-cli/issues/21477) )
An `--overwrite` flag needs to be added.

DX-1856 Add --overwrite flag

---

resources/release-notes.md

A release filled with leftovers before we clock out for summer. Mostly small fixes in code examples and tables, but the most important additions are the new fields added in the [paid resource model][resource-model-paid]. Have a great summer!

Release 3.1.1 (develop)

---

LICENSE
README.md

- Changes license from MIT to Apache 2.0.
- Adds badges for Contributor's License Agreement, Code of Coduct, Codacy and License.

DX-1904: Update license and badges

---

_includes/autoclick.md
_includes/payment-order-checkout-business.md
_includes/payment-order-checkout-enterprise.md
_includes/payment-order-checkout-payments-only.md
_includes/payment-order-checkout-starter.md
_includes/payment-order-purchase.md
_includes/payment-order-recur.md
_includes/payment-order-unscheduled.md
_includes/request-delivery-info.md

Removed
requestDeliveryInfo:true,
restrictedToDeliveryInfoInstruments: true
from all “basic” code examples in checkout v3. They are kept as optional feature sections only.
Removed Swish fields (age limit etc.) from all payment order code examples. They are kept in the Swish payment instrument only.

DX-1907: Remove requestDeliveryInfo and Swish Hotfix (master)

---

resources/release-notes.md

We have been picking up steam since our summer break, hitting full throttle as September arrived. A smaller release this time around, but there are some important additions nonetheless. We have added a siteId field to checkout v3 implementations, re-worked nearly all headers across the portal to make navigation easier, added a section on deleting payment tokens, along with the usual batch of assorted bug fixes and typos.

Release 3.1.2 (develop)

---

resources/release-notes.md

Another short and sweet one. We've added Checkout v3 paid responses for all instruments in both status and resource models, finished up the headers which was missing, added MobilePay to Request Delivery Information and done away with some more bugs and typos.

Release 3.1.3 (develop)

---

_includes/moto.md
payment-menu/features/optional/moto.md

Fixed the issues listed in the task. As the MOTO section won't be added to any other payment instruments now that we have a payment-order-moto.md, I hard coded it.
I am however, a bit puzzled as to why the transaction list response on the Card MOTO page is showing paymentorders, as there is a documentation_section if/else that should be taking care of it in transaction-list-response.md.
Help?

DX-1791: Card MOTO Fixes

---

resources/release-notes.md

Even with an autumn break (with Swedbank Pay colors everywhere you look), there are two big ones this time around. We now offer **Click to Pay** for both Redirect and Seamless View in all four Checkout v3 implementations.  We have also added a new capability called Cross Channel Payments, which we hope you read up on! Apart from that, there are no releases without typo corrections and bug fixes.

Release 3.1.4 (develop)

---

_includes/payment-order-checkout-starter.md
checkout-v3/starter/introduction.md
checkout-v3/starter/seamless-view.md

Removed requireConsumerInfo as requested by Øyvind K, as it is deprecated.

DX-1953: Removed requireConsumerInfo from Starter

---

resources/release-notes.md

15 December 2022
Version 3.1.6
Our last update in 2022 mainly consists of clean-ups and fixes, but the most important changes are bin and msidn fields added (where they are relevant) to the Paid resource model and Paid status model, plus a small rework of Age restrictions.
Happy holidays, everyone! We look forward to seeing you in 2023!

Release 3.1.6 (develop)

---

Gemfile
Gemfile.lock
index.md

Explicitly adds the `rouge` Gem version `4.0.1` so we are certain the latest version is used, as doesn't seem to be the case after #1666. Also adds missing indentation to `index.md` to fix the blank front-page.

DX-1996: HTTP QUERY support

---

resources/release-notes.md

We kick off the new year with a new field in our payment order request. Your Checkout v3 implementation of choice is now added in the request, and it is mandatory for our business implementation. **Version 2 of the balance report and transaction list** is our second newcomer this release. Head over to Settlement & Reconciliation to learn more.
Checkout v2 and Payment Menu now has a paid status model, and the update payment order section is added for Checkout v3.

Release 3.1.7 (develop)

---

.github/workflows/test.yml

Set RubyGems explicitly to version `3.3.22` to avoid [these kinds of build errors](https://github.com/SwedbankPay/developer.swedbankpay.com/actions/runs/4014043509/jobs/6894150855).

DX-2028: Set RubyGems version to 3.3.22

---

Gemfile
Gemfile.lock
resources/release-notes.md

Bigger things are coming up around the bend, so we are stopping by with some smaller fixes and a Checkout v3 matrix giving you a better overview over which payment instruments v3 has to offer, and the countries they are available.
We'll be back soon!

Release 3.1.8 (develop)

---

.github/mergify.yml
Gemfile
Gemfile.lock

Downgrade theme from version 2.0.0 to version 1.16.2. Again! With https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1708#issuecomment-1411797979, there's hope it will stay ignored this time.
Reverts #1708.

DX-2028: Downgrade theme from 2.0.0 to 1.16.2

---

resources/release-notes.md

Version 4.1.0
A lot of changes are happening these days. We've made the decision to focus the Checkout v3 offering, so our Starter and Business implementations are no more. This means that we can do what we do best: giving you a payment experience packed with options. The Payments Only implementation is still here, and for those of you with a Strong Consumer Authentication who want access to our safely stored card data, Enterprise is still available too.
Changes
DX-2072: Small amount correction after feedback @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1748)
DX-2069: Removed Verify options for recurrenceTokens @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1747)
DX-2031: Updated quantity field from integer to number …

Release 4.1.0 (develop)

---

resources/release-notes.md

24 April 2023
Version 4.2.0
The keen observer might spot some changes in our menu. The Checkout v2, Payment Menu and Payment Instruments have been moved to Old Implementations. You can still find everything you want and need, so no need to worry. A new .NET SDK section has also been added, in addition to the usual bugs and small fixes.
Documentation
DX-2093: Added Credit Account Disclaimer @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1773)
DX-2084: Removed including - from payeereference @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1772)
DX-2092: Replaced paymentorder with paymentOrder @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1771)
Pax terminal net section @the-anders-jarold …

Release 4.2.0 (develop)

---

checkout-v3/resources/release-notes.md

We had time for one more before we clock out for summer, so we added a PATCH example to our Payout feature section. Go check it out if you are on your way to implementing it.
Have a great summer!

Release 4.3.3 (develop)

---

_includes/payout.md

Changed enterprise to payments only and removed direct as integration.

Hotfix: DX-2163 Payout PATCH response (master)

---

checkout-v3/resources/release-notes.md

Today, we go live with Payment Order v3.1, which has some changes in the request, the post-purchase operations and the callback. We have also added a new resource model called failedPostPurchaseAttempts. Go check it out!
There is a new section regarding Trustly in Digital Payments, with important information regarding overlay and Trustly Express.
There is also a new Vipps field for fees in the failedAttempts resource model, and the quick links to test data and other resources have been moved from the front page to Digital Payments.

Release 4.6.0 (develop)

---

checkout-v3/index.md
pax-terminal/index.md

The pax and digital payments had a "newest release notes" that were very close to the regular feed and seemed excessive.

DX-2308: Removed duplicate release notes from intro pages

---

checkout-v3/release-notes.md

We spent some time building up steam after new years, but we have lots of treats lined up.
Are you looking to get started with recurring payments, but not really sure where to start? We have compiled everything you need in a use case and walk you through it all.
Or are you maybe looking to upgrade to our newest Digital Payments version? See how easy it is in our migration guide.
A new errorType goes live any day now, so a preview in the developer portal seems fitting. The aim is to give you clearer feedback when a token has become inactive. Read more about it in the problems section.
We have also made improvements to the domain verification steps of our Apple Pay documentation.
The Resources are being split up. We have moved the test-data and release notes up a level for convenience. …

Release 4.7.0 (develop)

---

checkout-v3/release-notes.md

We strive to make the implementation process as easy as possible, and in that regard, a Get Started section has been introduced. This now includes the basic requests and responses, how to display the UI, post-purchase options and other useful information when doing a basic integration.  The newest addition is an explanation on how to validate the status of the payment.
A new feature for those of you who want to customize the order of your payment menu has also seen the light of day, together with the possibility to expand the top instrument. They can be used independently, but work great together.
We also did a handful of bug fixes and corrections to improve usability and readability.
DEVP-347: cleanup before release 5.0.0 @arebra …

Release 5.0.0 (develop)

---

_config.yml
checkout-v3/modules-sdks/mobile-sdk/android.md
checkout-v3/modules-sdks/mobile-sdk/bare-minimum-implementation.md
checkout-v3/modules-sdks/mobile-sdk/configuration.md
checkout-v3/modules-sdks/mobile-sdk/custom-backend.md
checkout-v3/modules-sdks/mobile-sdk/features/index.md
checkout-v3/modules-sdks/mobile-sdk/index.md
checkout-v3/modules-sdks/mobile-sdk/ios.md
checkout-v3/modules-sdks/mobile-sdk/merchant-backend-sample-code.md
checkout-v3/modules-sdks/mobile-sdk/merchant-backend-v2.md
checkout-v3/modules-sdks/mobile-sdk/merchant-backend.md
checkout-v3/modules-sdks/mobile-sdk/plain-webview.md
checkout-v3/modules-sdks/mobile-sdk/process-diagrams.md
checkout-v3/payment-presentations.md

In this PR, we've made several improvements to the Mobile SDK documentation chapters.
* Restructure of the documentation to prioritise the more common Custom Backend approach to implement the mobile SDK, and with that moved the Merchant Backend API instructions down in order.
* Added a new chapter for a Bare Minimum Implementation of the SDKs on both iOS and Android to get a better grasp of the SDKs and enable the merchant to present the payment UI in their app with as few steps as possible.
* Additions and smaller fixes for the Apple Pay integration guide, mainly covering the option for merchants to use a plain web view without the mobile SDKs and still use Apple Pay as an instrument.
* Fixing spelling errors, broken links, outdated code examples, etc.
* Added Mobile SDK versions as …

SDK-1: Update of Mobile SDK documentation

---

_includes/use-case-recurring.md
checkout-v3/index.md

ESY-6972 Decorate use case card with supported payment method(s)
https://payexjira.atlassian.net/browse/ESY-6972
Also fixed error in code example

ESY-6972 Decorate use case card with supported payment method(s)

---

checkout-v3/modules-sdks/mobile-sdk/bare-minimum-implementation.md
checkout-v3/modules-sdks/mobile-sdk/native-payments.md

In this PR, we're adding documentation for presenting web based payments in the new session methods in the mobile SDK.

SDK-25: Web View based instruments from Native session
