SwedbankPay/developer.swedbankpay.com

checkout/payment.md
Change "all properties are optional" to "most properties are optional".
=> Not all properties are optional

resources/demoshop.md, resources/development-guidelines/code-of-conduct.md, resources/development-guidelines/contributing.md, resources/development-guidelines/good-commit-practice.md, resources/development-guidelines/index.md, resources/development-guidelines/licence.md, resources/index.md, resources/test-data.md
Copied development guidelines over to resources section
=> Added development-guidelines to Resources section

payments/vipps/other-features.md
Fix what seems to be the remnants of a bad merge in Vipps other features.
=> Fix intro in vipps other features

payments/credit-account/after-payment.md, payments/credit-account/index.md, payments/credit-account/other-features.md
Updated credit account section with links, and max line length of 80.
=> DX-258 Credit account section

resources/index.md
=> Fix forgotten ## mark in resources

checkout/summary.md
Reported in Slack, added by me now,
=> Added missing link to summary

payments/swish/after-payment.md
Missing periods.
Take this into develop before you do next  master merge.
=> Small textual fixes in swish after payment.

checkout/other-features.md
Undo overzealous search and destroy in 398ddfbc7da008eec5db842c97b3496304c31b8f.
=> Undo overzealous search and destroy

checkout/other-features.md, index.md
More und of overzealous search and destroy in  398ddfbc7da008eec5db842c97b3496304c31b8f.
=> More undo of overzealous search and destroy

README.md, _includes/abort-reference.md, _includes/callback-reference.md, _includes/one-click-payments.md, _includes/operations-reference.md, _includes/payeeinfo.md, _includes/payment-order-cancel.md, _includes/payment-order-capture.md, _includes/payment-order-reversal.md, _includes/recurring-card-payments.md, _includes/settlement-reconciliation.md, _includes/subsite.md, _includes/urls.md, checkout/after-payment.md, checkout/checkin.md, checkout/payment-menu.md, index.md, payments/credit-card/after-payment.md, payments/credit-card/other-features.md, payments/direct-debit/redirect.md, payments/index.md, payments/swish/after-payment.md, payments/vipps/after-payment.md, payments/vipps/index.md
Various fixes and improvements
=> Various fixes and improvements

payments/vipps/index.md
Remove stray backslashes in Vipps
=> DX-272: Remove stray backslashes

resources/test-data.md
Updated to correct zip code on Swedish test user, Leia.
=> DX-496 updated zip code on Swedish test user

payments/index.md
A first attempt at an introduction page.
=> Payments introduction, first attempt

_includes/payment-resource.md, payments/invoice/other-features.md
Removed occurrences of credit card from invoice other features.
=> DX-518 Removed occurrences of credit card

_includes/payment-order-reversal.md, payments/card/index.md, payments/card/redirect.md
Replaced request with Patrick's new example which included order items
=> Included order items in the request body

payments/invoice/index.md
Added separate addresses for Finland, Norway and Sweden.
=> Fixed country specific email addresses for setup

_includes/authorizations-resource.md, _includes/one-click-payments.md, _includes/payment-resource.md, _includes/prices.md, _includes/transactions.md, checkout/checkin.md, payments/card/after-payment.md, payments/credit-account/after-payment.md, payments/direct-debit/redirect.md, payments/mobile-pay/other-features.md
This fixes a few small errors around the project
=> various small fixes

payments/card/other-features.md, payments/card/seamless-view.md
Will add the state section as a separate task.
=> 4 out of 5 card blockers requested from Patrick

payments/index.md, payments/swish/index.md
Removed Web invoice from the list in payments intro.
Did some textual changes after feedback from Magnus Bergh in Swish.
=> Small changes after wishes from Cato and Magnus

resources/test-data.md
@geir-straume found one that does not work
=> Removed amount error testing that does not work

payments/card/redirect.md
Added a link which Patrick requested.
=> Added link to payment/transaction states.

README.md, payments/card/after-payment.md, payments/card/index.md, payments/card/other-features.md, payments/card/redirect.md, payments/card/seamless-view.md, payments/index.md, resources/release-notes.md
* Release payments and card payments sections
=> Release 1.6.2 (develop)

resources/release-notes.md
* `restrictedToInstruments` added to payment-order-purchase.md
* `Direct Debit` section and mentions in various includes removed
* `remote_theme` updated in config.yml
* `unitPrice` in [payment-order-purchase.md updated
* `MobilePay` typos fixed
=> Release 1.6.3 (develop)

checkout/payment-menu.md
1. Updated the request to the checkin endpoint to match the new input.
- The request content that was shown in the documentation was the old input. This has been replaced with operation, language and shippingAddressRestrictedToCountryCodes, to match the checkin documentation.
2. Removed the window.onLoad wrapper around the js code
- If the proposed change sent earlier to the checkin applies, this will reflect the same change (by moving the script tag out of the head and to the bottom of the body instead).
=> Updated JavaScript section

checkout/checkin.md
1. Moved the script from the head of the file to the bottom of the body.
- This means you no longer have to run a "window.onload" and that the page can load without having to wait for the script to be downloaded / loaded in.
2. Updated the JavaScript section to match the changes in [1]
- With the script on the bottom of the body, it will now load last, which means all the DOM elements it tries to access will be loaded and accessable.
3. Updated the info section after the Javascript section to reflect this change.
- Simply explaining the reasoning to why you need to place the script at the end as per [2].
=> Changes to the sample code and explanations

_includes/payment-order-purchase.md
Add missing comma to code example
=> Add missing comma

resources/data-protection.md, resources/demoshop.md, resources/index.md, resources/public-migration-key.md, resources/release-notes.md, resources/terminology.md, resources/test-data.md
Reformat the public migration key page and add it to the resources menu.
=> Reformat public migration key page

_config.yml, _includes/card-problem-messages.md, _includes/create-authorization-transaction.md, _includes/create-payment.md, _includes/merchant-authenticated-consumer.md, _includes/payout.md, _includes/recur.md, _includes/unscheduled-purchase.md, _includes/verify.md, payments/invoice/other-features.md, resources/test-data.md
Replaces `camelCased` variables with their `snake_case` replacements and ensures consistent variables use across the board.
=> Variable fixes

resources/test-data.md
This isn't very useful for our merchants, so I removed it.
=> Removed callback section.

payments/swish/direct.md
After request from Mike Hellberg.
=> DX-729 Added mCommerce request and response.

resources/release-notes.md
* Described the M-Commerce flow for Swish Direct.
* Alphabetize the terms in Terminology.
=> Release 1.7.4 (develop)

resources/release-notes.md
* Several links has been corrected. The chance of 404 is now much lower.
* Other small text changes and clarifications.
=> Release 1.7.6 (develop)

checkout/checkin.md, checkout/payment-menu.md
added steps to checkin and payment menu after a small workshop with the developers. Moved both sequence diagrams to the bottom of each page.
=> dx-692 added steps to checkin and payment menu

payments/invoice/direct.md, payments/invoice/redirect.md
Added more code examples after discussions with Syver. 
Changed the `approvedLegalAddress`to be valid for SE and NO, as in previous documentation.
=> Dx 810 restructure direct invoice

_includes/field-description-id.md, checkout/other-features.md
Should I just add a generic "Payment failed" text in details?
=> dx-839 Added the onPaymentTransactionFailed event in the checkout section.

checkout/other-features.md
As I said in the commit, I know this looks horrible. It would be great if it looked like this: 
https://wiki.payex.com/xwiki/wiki/stagedeveloper/view/Main/ecommerce/payex-checkout-main/payex-checkout-recurring-payments/
=> dx 724 recurring flow chart

payments/invoice/seamless-view.md
REstructured the seamless view section for Invoice
=> dx-808 Restructured into steps.

_includes/payee-info.md, checkout/other-features.md, payments/mobile-pay/other-features.md, payments/swish/other-features.md, payments/vipps/other-features.md
fixed payeereference in payeeinfo and included this in all payments we have (?)
=> dx-804 fix the payeereference in payeeinfo

payments/card/direct.md, resources/release-notes.md
Release Notes
* Added a more thorough description on `paymentUrl` and `completeUrl` in all relevant
payments.
* Updated orderItem to be required in all requests and responses.
* Clean up of .Swish Payments
* Removed pageStripDown in Vipps Redirect.
* Updated Card Payments Direct to have a correct integration
flow.
* Updated the main page to be more welcoming.
* Updated information on Merchant Authenticated Consumer.
* Added docker files, updated remote references and workflow file.
=> Release 1.8.2 (develop)

_config.yml, _includes/authorizations-resource.md, _includes/card-general.md, _includes/expand-parameter.md, _includes/one-click-payments.md, _includes/payment-link.md, _includes/payment-url.md, _includes/recurring-card-payments.md, _includes/verify.md, checkout/after-payment.md, checkout/checkin.md, checkout/index.md, checkout/other-features.md, checkout/payment-menu.md, payments/card/direct.md, payments/card/index.md, payments/card/redirect.md, payments/index.md, payments/invoice/direct.md, payments/invoice/index.md, payments/invoice/other-features.md, payments/invoice/seamless-view.md, payments/swish/direct.md, resources/release-notes.md
Updating to theme v1.4.1 fixes Mermaid styling and improves the styling of code blocks.
=> DX-889: Fix mermaid styling

resources/release-notes.md
* Bug fixes to Mermaid diagram and alert styling, plus improvements to code block styling after the update to [Swedbank Pay Design Guide][design-guide] 4.5.0.
* Added examples with screenshots of the effects of [Merchant Authenticated Consumer][mac-checkout].
[design-guide]: https://design.swedbankpay.com/
[mac-checkout]: /checkout/other-features#merchant-authenticated-consumer
=> Release 1.8.3 (develop)

payments/swish/other-features.md
Small url fix in Swish. Made sure all other Payments and Checkout have the corrects urls
=> dx-898 additional url fix

resources/release-notes.md
* Added new section SDKs and Modules in Resources.
* Corrected URL links for Error and Problem sections for Card Payments,
* Checkout and Swish Payments.
* Added new icon tag for table required checkmarks.
* Added new flag images.
=> Release 1.9.0(develop)

.github/workflows/rebase.yml
Update rebase workflow to v1.3 to support rebasing of PR's from forks.
=> Update rebase workflow to v1.3

payments/invoice/after-payment.md, payments/invoice/capture.md, payments/invoice/redirect.md, payments/invoice/seamless-view.md
fixed capture and removed card from invoice payments
=> dx-908 url and card fixes in invoice payments

_includes/alert-callback-url.md, payments/swish/direct.md, payments/swish/redirect.md, payments/swish/seamless-view.md
Only fixed mcom and ecom Direct and Redirect in this pull request. Swish Seamless view will be in a separate. Set callback to alternative because I feel its a bit less misguiding than optional (?) please give feedback :)
=> Dx 873 swish seq diagrams

_includes/payment-order-capture.md
=> dx-932 fixed broken links in Capture Checkout

resources/release-notes.md
Version 1.9.1
* Corrected sequence diagrams in Swish Payments and Vipps Payments.
* The `description` field is now more thoroughly described for all requests it's present in.
* The `language` field is now better described for all requests it's present in.
* All broken links should now be unbroken.
=> Release 1.9.1 (develop) 

.githooks/commit-msg, .githooks/prepare-commit-msg, checkout/other-features.md
Fix navigation typo in Checkout Other Features. Also makes the Git commit message hooks case insensitive.
=> DX-947: Fix navigation typo in Checkout Other Features

_config.yml, resources/release-notes.md
Release notes  1.10.0
* Added a new Gift Cards section with descriptions of our Gift Cards API.
* Added a new section Co-badge Card Choice for Dankort in Card Payments.
=> Release 1.10.0 (develop)

_includes/payment-link.md, _includes/verify.md, payments/card/index.md, payments/card/redirect.md, payments/card/seamless-view.md, payments/invoice/other-features.md, payments/payment-link.md, payments/swish/redirect.md, payments/swish/seamless-view.md, payments/vipps/index.md, payments/vipps/redirect.md, payments/vipps/seamless-view.md, resources/development-guidelines/index.md
Make the documentation gender neutral as requested in https://github.com/SwedbankPay/developer.swedbankpay.com/issues/372#issuecomment-623373794.
=> Dx 924 gender neutral documentation

.docker/docker-compose.ci.yml, .github/workflows/build_and_deploy.yml, docker-compose.yml
DX-955: Upgrade to v1.3.2 of `jekyll-plantuml`.
=> DX-955: Upgrade to v1.3.2 of jekyll-plantuml (develop)

.docker/docker-compose.ci.yml, .github/workflows/build_and_deploy.yml, docker-compose.yml
DX-955: Upgrade to v1.3.2 of `jekyll-plantuml`.
=> DX-955: Upgrade to v1.3.2 of jekyll-plantuml (master)

.docker/docker-compose.test.yml, .github/workflows/repository_metadata.sh, .github/workflows/verify_build_output.yml, .markdownlint.yml, Rakefile, checkout/other-features.md, index.md
Added 'orderReference' in payment order callback.
=> DX-878: Updated callbackresponse

.githooks/commit-msg, .githooks/pre-commit, .githooks/prepare-commit-msg, .github/tests/commit-msg-test.sh, .github/workflows/githooks.yml, .github/workflows/repository_metadata.sh, Rakefile
Adds `shellcheck` and fixes the problems it finds.
=> DX-962: Add shellcheck

resources/release-notes.md
Release notes:
* Updated Swish Redirect requests.
* Added `orderReference` information in Payment Order Callback in Checkout Other features.
* Updated docker image
* Updated spring security link
* Added CD script for deploying
=> Release 1.10.1(develop) 

docker-compose.yml, resources/release-notes.md
Release notes 1.11.0
* Added a new Trustly Payments section.
* Added information about Storing URIs in the Technical
Information section.
* Added new icon tags
* Updated codebase to adhere to Codacy rules
=> Release 1.11.0(develop)

.remarkrc.yaml, CODEOWNERS, package-lock.json, package.json
This pull request removes a error message reported by Codacy.
It also closes a security warning reported by DependaBot!
=> Remove remark-slug from config

resources/release-notes.md
Version 1.11.1
*   Added additional information on the settlement files in Settlement &
Reconciliation for all Payments.
*   Corrected sequence diagrams til Card Payments Redirect and Card Payments
Seamless View.
*   Added Abort in Swish Payments.
*  Updated to use the Design Guide flags in Developer portal
*  Updated Jekyll plantuml docker
=> Release 1.11.1 (develop) 

resources/release-notes.md
Version 1.13.0
Added information on Mobile SDK in Modules & SDKS section.
Added tables for mapping API fields in settlement files in Settlement and Reconciliation.
=> Release 1.13.0 (develop) 

_includes/payment-order-other-features.md
Where in other features should this be placed ?
And is it a bit too long ?
=> dx-1124 added description on Payer Aware in Payment Menu other features

payments/trustly/other-features.md, payments/trustly/redirect.md
Fixed code examples after feedback that cancelUrl was missing.
=> dx-1153 Added cancelUrl in code examples.

docker-compose.yml, payments/trustly/index.md, payments/trustly/other-features.md
Added lists for Sweden and Finland
=> Feature/dx-1141 List of banks for Sweden and Finland

resources/release-notes.md
Version 1.13.2
* Added description on metadata for all payment instruments.
* Updated files in Settlement & Reconciliation.
* Added info on token deletion in Card Payments and Invoice Payments.
* Updated the documentation on paymentRestrictedToAgeLimit and
paymentRestrictedToSocialSecurityNumber in Swish Payments.
* Added documentation on guest checkout in Checkout.
* Updated information about logourl in Checkout.
* Added a list of accepted banks in Trustly Payments.
* Updated the UpdateOrder description in Checkout.
=> Release 1.13.2(develop) 

_includes/payment-resource.md
Authroization --> Authorization
=> dx-1155 Fixed typo

resources/test-data.md
The intention was fix the "through specific" typo, but the whole paragraph felt somewhat corny, so I re-wrote it.
=> dx-1156 Typo in test data

_includes/problems/generic.md, _includes/problems/trustly.md
Added documentation for problems specific to Trustly.
=> ESF-956 Documented Trustly problems

_includes/field-description-language.md, payments/mobile-pay/other-features.md, payments/mobile-pay/redirect.md
https://payexjira.atlassian.net/browse/ESY-1972
=> ESY-1972 Remove msisdn prefill from documentation, clarify shoplogoUrl

_includes/payee-reference.md
Tried to ad an if so that PayeeReference for card payments has string(50) and the rest have string(30).
=> dx-1162 Card Payments PayeeReference string

_includes/logo.md, modules-sdks/index.md
Updates the links in Modules & SDKs.
=> DX-1083: Update Modules & SDKs links

README.md
Rewrote large parts of the `README` to document how forking is necessary if the author doesn't have write-access to the developer.swedbankpay.com repository.
=> DX-1161: Rewrote README to take forking into account

resources/test-data.md
Added information that we are going towards the POS system.
=> dx-1170 Test data edit

_includes/delete-token.md
Added instrumentdata/ and a , after the comment.
=> dx-1171 PATCH correction instrumentdata

_includes/alert-gdpr-disclaimer.md
Wrote the include. Hasn't been included anywhere yet.
=> dx-1210 Wrote gdpr disclaimer

checkout/payment-menu.md, payment-instruments/card/direct.md, payment-instruments/card/redirect.md, payment-instruments/card/seamless-view.md, payment-instruments/invoice/direct.md, payment-instruments/invoice/redirect.md, payment-instruments/invoice/seamless-view.md, payment-instruments/mobile-pay/redirect.md, payment-instruments/swish/direct.md, payment-instruments/swish/redirect.md, payment-instruments/swish/seamless-view.md, payment-instruments/trustly/redirect.md, payment-instruments/trustly/seamless-view.md, payment-instruments/vipps/redirect.md, payment-instruments/vipps/seamless-view.md, payment-menu/payment-order.md
Added it where it seemed appropriate for now.
=> dx-1211 Added the GDPR disclaimer

_includes/field-description-vatamount.md
Corrected what will be displayed on the payment page.
=> dx-1246 Incorrect VAT info

.github/workflows/auto-review-pull-requests.yml, Gemfile, Gemfile.lock
- Updates theme to version 1.9.0
- Adds a GitHub workflow that should automatically approve pull requests from Dependabot
=> Update theme to version 1.9.0

404.md, checkout/after-payment.md, checkout/capture.md, checkout/index.md, checkout/other-features.md, checkout/payment-menu.md, docker-compose.yml, gift-cards/index.md, gift-cards/operations.md, gift-cards/other-features.md, gift-cards/security.md, modules-sdks/index.md, modules-sdks/mobile-sdk/index.md, payment-instruments/card/after-payment.md, payment-instruments/card/capture.md, payment-instruments/card/index.md, payment-instruments/index.md, payment-instruments/invoice/index.md, payment-instruments/mobile-pay/index.md, payment-instruments/swish/index.md, payment-instruments/trustly/index.md, payment-instruments/vipps/index.md, payment-menu/after-payment.md, payment-menu/capture.md, payment-menu/index.md, payment-menu/other-features.md, payment-menu/payment-order.md, resources/development-guidelines/index.md, resources/index.md
Some fixes after upgrading the theme to 1.9.3
=> DX-1263: Theme fixes

payment-instruments/card/other-features.md
=> Added link to TransactionOnFile

index.md, resources/release-notes.md
Version 2.0.0
Launched new developer portal theme:
*   New design
*   New menu structure
*   Reading time
Other changes:
*   Added GDPR disclaimer.
*   Added custom 404 page.
*   Added Transaction on File section.
*   Added Seamless View for Trustly.
*   Added documentation about payment states in Card Other Features.
*   Added event overrides warning for Card Seamless View Events.
*   Added section regarding MOTO in Card Other Features.
*   Deleted Merchant Identified Payer in Checkout
*   Renamed Merchant Authenticated Consumer to Delegated Strong Consumer Authentication
*   Updated `payer`/`consumer`/`end-user` naming for most sections.
*   Updated expiry date for test cards in test data.
*   Updated callback documentation.
*   Updated regex pattern for `orderItems.class`.
=> Release 2.0.0 (develop)

payment-instruments/card/other-features.md
Removed moto section from card other features.
=> dx-1293 MOTO removal

resources/release-notes.md
Version 2.0.1
* Added section for MobilePay Seamless View
* Split MobilePay Capture to a separate page
* Code examples for digital products added in Checkout
* Removed MOTO
* Fixed code example and image link in Transaction on File for Payment Menu
=> Release 2.0.1 (develop)

payment-instruments/vipps/redirect.md
Removed the shopping cart paymenturl link.
=> DX-1297 Vipps redirect link

index.md
=> Added gift cards

_includes/delete-token.md
Added the correct response to the PATCH delete recurrence token section for checkout.
=> DX-1286 add correct delete token response

resources/release-notes.md
Version 2.0.2
* Various bug fixes
* Various corrections and typo fixes
* Corrected information about 3D-Secure
* Added paragraphs about different consumer flows in Checkin
* Added link to gift card on the front page
=> Release 2.0.2 (develop)

_includes/payment-order-other-features.md, introduction.md
Moved the alert from payment order other features, re-wrote it and added it to the introduction.
=> DX-1322 Postel's Law

_includes/callback-reference.md
Added an alert and added a sentence on response times.
=> DX-1443 Clarified that callback is a fail-safe

_includes/settlement-reconciliation.md
=> DX-1294 Improve subsite wording

modules-sdks/mobile-sdk/android.md, modules-sdks/mobile-sdk/configuration.md, modules-sdks/mobile-sdk/custom-backend.md, modules-sdks/mobile-sdk/index.md, modules-sdks/mobile-sdk/ios.md, modules-sdks/mobile-sdk/merchant-backend.md, modules-sdks/mobile-sdk/plain-webview.md, modules-sdks/mobile-sdk/process-diagrams.md
Include documentation about custom backends.
=> Update Mobile SDK documentation

index.md
Removed wording which could be confusing.
=> DX-1447 gift cards rewording.

_includes/prices.md
Fleshed out the prices info and type info.
=> DX-1428 Revisit Prices

payment-instruments/invoice/other-features.md, payment-instruments/swish/direct.md, resources/release-notes.md
* Updated theme with visual fixes
* Search icon is now clickable
* Various bug fixes
* Various corrections and typo fixes
* Re-worded split settlement
* Clarified that callback is a fail-safe
* Updated tables and code examples with payerReference in various places, like card purchase
* Updated Mobile SDK configurations for both iOS and Android to include integration with custom backends
* Updated Mobile SDK to newest versions
* Re-wrote Prices section
=> Release/2.1.0 (develop)

resources/release-notes.md
Fixed version number from 2.0.1 to 2.1.0
=> Hotfix (master) 2.1.1

.github/autolabeler.yml, .github/pr-labeler.yml, .github/workflows/pr-labeler.yml
This PR adds [probot-autolabeler](https://github.com/apps/probot-autolabeler) and [pr-labeler-action](https://github.com/TimonVS/pr-labeler-action) to automatically label pull requests based upon their file contents and branch naming.
=> Automatic pull request labelling

Gemfile.lock, resources/release-notes.md
* Updated Theme version to 1.9.9
* Updated Design Guide Version to 5.0.1
=> Release 2.1.2(develop)

Gemfile, Gemfile.lock
=> Bump theme to version 1.9.10

index.md, payment-menu/after-payment.md, payment-menu/capture.md, payment-menu/index.md, payment-menu/other-features.md, payment-menu/payment-order.md
Release Payment Menu to production.
=> DX-1500: Payment Menu in production (master)

_includes/tra.md, checkout/2.0/features/index.md, checkout/2.0/features/optional/index.md, checkout/2.0/features/optional/tra.md
Changed the URL that said checkout/2.0/paymentorders (needs a permanent fix)
Added a requestTraExemption bool which Øyvind forgot.
Renamed to TRA Exemption at Øyvinds request.
=> DX-1504: TRA fixes

checkout/3.0/index.md, checkout/index.md
Removed Estimated reading times that said "-"
Added correct icon to Checkout 3.0 options.
=> DX-1506: Removed estimated reading time

_includes/payment-order-purchase.md
Chanched instrument to null and added RTI in order items.
=> Hotfix/dx-1495 payment menu instrument to null and restrictToInstruments fixes (master)

.github/release-drafter.yml
Change Release Drafter's order of categories to hopefully affect how issues are categorized.
=> DX-969: Change the order of categories

payment-instruments/invoice/direct.md
Switched from dotted to solid lines for POST approvedLegalAddress and Update payment with payer's delivery address in the flow chart.
=> DX-1519: Fixed approvedLegalAddress in the direct flow chart

_includes/alert-ip-address.md, modules-sdks/mobile-sdk/android.md
Except getconf, which appears to be gone. Pertti is working on a fix and will provide new link.
=> DX-1526: Updated android sdk links

_includes/callback-reference.md
=> Hotfix/dx-1510 hotfixing the callback ip address (master)

_includes/payment-order-purchase.md
Added instrument in the checkout section.
=> DX-1529: Fixed checkout example after the "payment menu instrument to null" task

_includes/payment-order-purchase.md, _includes/verify.md
Small comments from Per
* Add unscheduledToken to PO purchase
* Hide unscheduledToken from Verify when not through paymentOrder (paymentMenu/checkout)
* Hide paymentToken when using checkout
=> ESY-2578 Add unscheduled token to po purchase, hide paymenttoken from co

_includes/payment-order-purchase.md
The other parts are visible in payment menu.
=> DX-1531: Changed the if so only consumerprofileref is present in checkout

_includes/card-authorization-transaction.md, _includes/instrument-mode.md, _includes/metadata.md, _includes/payment-order-purchase.md, _includes/payments-operations.md, checkout/v2/payment-menu.md, payment-instruments/card/after-payment.md, payment-instruments/invoice/direct.md, payment-instruments/mobile-pay/seamless-view.md, payment-instruments/swish/direct.md, payment-instruments/swish/redirect.md, payment-instruments/swish/seamless-view.md, payment-instruments/trustly/redirect.md, payment-instruments/trustly/seamless-view.md, payment-instruments/vipps/after-payment.md, payment-instruments/vipps/redirect.md, payment-instruments/vipps/seamless-view.md, payment-menu/payment-order.md
=> DX-1535: Fix response examples

_includes/tra.md
Missing comma in code example. Time to run `git blame`? 😄 
Don't worry, I won't tell.
=> Fix code example in tra.md

_includes/instrument-mode.md
=> DX-1514: Disclaimer for instrument mode

checkout/v2/checkin.md
Added in Checkout v2 Checkin section. Will add it in the v3 sections in the v3 task.
=> DX-1585: Document that consumerProfileRef will expire after 24 hours.

modules-sdks/mobile-sdk/ios.md
iOS SDK now supports SwiftPM. Added instructions for installation through SwiftPM.
=> Update iOS SDK documentation.

_includes/payment-order-get.md, modules-sdks/index.md
Added a list of tokens and descriptions in the table.
=> DX-1619: Hotfix Add tokens to paymentOrder GET response (master)

checkout/v3/index.md
=> DX-1645: Fixed a rookie mistake with the link to Checkout v3 Standard

_includes/languages.md, checkout/v3/authenticated/index.md, checkout/v3/mac/index.md, checkout/v3/payments/index.md, checkout/v3/standard/index.md
Went with the easy solution. Lets get fancy later.
=> DX-1650: Fixed languages in Checkout v3

.github/workflows/azure-production.yml, .github/workflows/azure-stage.yml, .github/workflows/test.yml, _includes/payment-order-capture.md
After request from Øyvind K.
(Still correct for payment instruments).
=> Hotfix DX-1669: Removed invoice specific parts of payment order capture section (master)

.vscode/settings.json, _includes/payment-order-recur.md
=> DX-1647 fix recur endpoint

checkout-v3/sequence-diagrams.md
This should fix the broken sequence diagrams. 
However, I am not sure if the changes affected the actual content of the diagrams.
My primary focus was to fix the broken diagrams. I would appreciate if someone could assist in verifying that the content is correct.
=> DX-1700 Diagram fixes

_includes/payment-order-checkout-business.md
Removed nationalIdentifier from request and table.
=> DX-1738: nationalIdentifier should not be in Checkout v3 Business

_includes/purchase.md
added "if" for seamless-view section in purchase include
=> DX-1666 Update Purchase operation

index.md
=> DX-1752: Fixed typo in v3 introduction.

checkout-v3/starter/seamless-view.md
Fixed a link SNAFU and added some new links.
=> DX-1753: Fix seamless view links.

checkout-v3/starter/features/technical-reference/delete-token.md, checkout-v3/starter/features/technical-reference/payment-state.md, checkout-v3/starter/features/technical-reference/resource-sub-models.md, checkout-v3/starter/features/technical-reference/status-models.md, introduction.md
suggestions for replacing credit card icons
=> DX-1739 feature icons

_includes/enterprise.md, _includes/payer-aware-payment-menu.md, _includes/payment-order-abort.md, _includes/settlement-reconciliation.md, checkout-v3/enterprise/introduction.md, checkout-v3/payments-only/introduction.md, index.md, payment-instruments/invoice/direct.md, payment-instruments/invoice/redirect.md, payment-instruments/invoice/seamless-view.md, resources/release-notes.md
Re-wrote the disclaimer and added it to redirect and seamless view as well, in accordance with Nina's request.
=> DX-1758: Changes to payment instrument invoice disclaimer

_includes/payer-aware-payment-menu.md
Red code and a weirdly placed sentence.
=> DX-1772: Final PAPM fix

checkout-v3/sequence-diagrams.md
=> DX-1765: Re-arrange sequence diagrams

_includes/api-resource.md
Copy of Ines bullet proof commit with a fresh develop to see if it helps.
=> DX-1759: Fix endpoints 2nd try

_includes/payment-order-recur.md, checkout-v2/features/optional/recur.md, checkout-v2/features/optional/unscheduled.md, checkout-v3/business/features/optional/recur.md, checkout-v3/business/features/optional/unscheduled.md, checkout-v3/enterprise/features/optional/recur.md, checkout-v3/enterprise/features/optional/unscheduled.md, checkout-v3/payments-only/features/optional/recur.md, checkout-v3/payments-only/features/optional/unscheduled.md, checkout-v3/starter/features/optional/recur.md, checkout-v3/starter/features/optional/unscheduled.md, payment-instruments/card/features/optional/unscheduled-purchase.md, payment-menu/features/optional/recur.md, payment-menu/features/optional/unscheduled.md
Fleshed out payment order recur and re-did the reading time.
=> DX-1548: Recurring re-write

resources/release-notes.md
Added a new card error code and restructured the tables.
Fleshed out the Unscheduled Purchase section.
Fleshed out the Recur section.
Moved the Callback section to core features.
Typos and minor bug fixes in code examples and tables.
=> Release 3.0.3 (Develop)

_includes/payment-order-checkout-starter.md
Fixed a code typo. Seems like the code example isn't the issue, as some credentials fail, and other work after a straight copypaste. Need to find out where they are getting their credentials and fix the issue in that end.
=> DX-1783: Starter seamless view code issue

resources/development-guidelines/contributing.md, resources/development-guidelines/index.md
=> DX-1807: Github links blocking version bump

_includes/autoclick.md
=> DX-1851: More Autoclick

_includes/instrument-mode.md
Added a first draft of the section.
=> DX-1843: Add Eligibility Check in Instrument Mode

modules-sdks/mobile-sdk/android.md, modules-sdks/mobile-sdk/ios.md
Changes reflect the implementation of V3 in the mobile SDK
=> Mobile SDK documentation additions

_includes/mobile-sdk-papm.md, _includes/mobile-sdk-tokens.md, modules-sdks/mobile-sdk/merchant-backend-v2.md
Updates on how patch have changed in V3, and specifically how this effects IntrumentMode
=> Instrument mode and patching of orders

_includes/payment-order-purchase.md
=> DX-1849: Fixed example amount

_includes/autoclick.md, checkout-v3/index.md
Added a paragraph about the payment menu and fixed some text in autoclick
=> DX-1840: Apple Pay cleanup

_includes/autoclick.md, _includes/checkout-v3-status-models.md, _includes/checkoutv3-purchase.md, _includes/instrument-mode.md, _includes/payer-aware-payment-menu.md, _includes/payment-order-abort.md, _includes/payment-order-checkout-business.md, _includes/payment-order-checkout-enterprise.md, _includes/payment-order-checkout-payments-only.md, _includes/payment-order-checkout-starter.md, _includes/payment-order-get.md, _includes/payment-order-moto.md, _includes/payment-order-operations.md, _includes/payment-order-purchase.md, _includes/payment-order-recur.md, _includes/payment-order-unscheduled.md, _includes/request-delivery-info.md, _includes/update-payment-order.md, checkout-v2/payment-menu.md, checkout-v3/business/redirect.md, checkout-v3/business/seamless-view.md, checkout-v3/enterprise/redirect.md, checkout-v3/enterprise/seamless-view.md, checkout-v3/payments-only/redirect.md, checkout-v3/payments-only/seamless-view.md, checkout-v3/starter/seamless-view.md, modules-sdks/mobile-sdk/custom-backend.md, modules-sdks/mobile-sdk/merchant-backend.md, payment-menu/payment-order.md
Added in all view-checkout, view-paymentorder, redirect-checkout and redirect-paymentorder examples.
=> DX-1866: Add trace id in href

_includes/instrument-mode.md
=> DX-1867: Eligibility Check fix number ?

_includes/one-click-payments.md
Clearified some text parts and added a code example for payment instruments.
=> DX-1844: William's one-click issues, instruments edition

_includes/request-delivery-info.md, checkout-v3/business/features/optional/request-delivery-info.md, checkout-v3/enterprise/features/optional/request-delivery-info.md, checkout-v3/payments-only/features/optional/request-delivery-info.md
Added a sentence about where it will appear in both text and table.
=> DX-1876: DevInfo payer node feedback

checkout-v3/business/features/optional/autoclick.md, checkout-v3/enterprise/features/optional/autoclick.md, checkout-v3/payments-only/features/optional/autoclick.md, checkout-v3/starter/features/optional/autoclick.md
=> DX-1877: Autoclick icon

_includes/instrument-mode.md
=> DX-1873: Even more Eligibility Check

checkout-v3/business/features/optional/request-delivery-info.md, checkout-v3/enterprise/features/optional/request-delivery-info.md, checkout-v3/payments-only/features/optional/request-delivery-info.md
=> DX-1882: Fixing request delivery info icon

checkout-v3/business/features/optional/request-delivery-info.md, checkout-v3/enterprise/features/optional/request-delivery-info.md, checkout-v3/payments-only/features/optional/request-delivery-info.md
=> DX-1882: Fix request delivery info

resources/release-notes.md
DX-1887: Removed sentence about trying it in our demoshop.
=> Hotfix: Removed demoshop comment from Apple Pay release notes (master)

_includes/mobile-sdk-papm.md, _includes/mobile-sdk-tokens.md, modules-sdks/mobile-sdk/merchant-backend.md
=> Removed consumers from V3

_includes/enterprise.md, checkout-v3/enterprise/features/optional/mac.md, checkout-v3/enterprise/features/optional/recur.md, checkout-v3/enterprise/features/optional/request-delivery-info.md, checkout-v3/enterprise/features/optional/tra.md, checkout-v3/enterprise/features/optional/unscheduled.md, checkout-v3/enterprise/features/optional/verify.md
=> DX-1869: V2 TRA and MAC redirects wrong

_includes/mobile-sdk-debugging.md, _includes/mobile-sdk-instrument-mode.md, _includes/mobile-sdk-observing-the-payment-process.md, _includes/mobile-sdk-papm.md, _includes/mobile-sdk-payment-order.md, _includes/mobile-sdk-tokens.md, _includes/mobilepay-payments-capture.md, modules-sdks/mobile-sdk/android.md, modules-sdks/mobile-sdk/custom-backend.md, modules-sdks/mobile-sdk/index.md, modules-sdks/mobile-sdk/ios.md, modules-sdks/mobile-sdk/merchant-backend-v2.md, modules-sdks/mobile-sdk/merchant-backend.md, modules-sdks/mobile-sdk/plain-webview.md, modules-sdks/mobile-sdk/process-diagrams.md
Header grooming in Mobile SDKs
=> DX-1900: Headers, Modules and SDKs edition

_includes/checkout-v3-resource-models.md, _includes/payment-order-recur.md, _includes/payment-order-unscheduled.md, _includes/unscheduled-purchase.md
Re-wrote and added new examples plus links.
=> DX-1889: Fixed how to get token info

_includes/payment-order-cancel.md
Added missing comma in code example
=> DX-1901: Missing comma in cancel request

payment-instruments/card/seamless-view.md, payment-instruments/invoice/seamless-view.md, payment-instruments/mobile-pay/seamless-view.md, payment-instruments/swish/seamless-view.md, payment-instruments/vipps/seamless-view.md
Changed scriptUrl from dev to externalintegration.
=> DX-1896: Wrong scriptUrl in Seamless View code example

_includes/checkout-v3-events.md, checkout-v3/starter/seamless-view.md
=> DX-1892: Emphasize importance of onPayerUnidentified

_includes/delete-payment-order-token.md, checkout-v3/business/features/optional/delete-token.md, checkout-v3/enterprise/features/optional/delete-token.md, checkout-v3/payments-only/features/optional/delete-token.md, checkout-v3/starter/features/optional/delete-token.md
Re-wrote somewhat, cleaned up and added payment token.
=> DX-1796: Add payment token to delete token section

.github/workflows/test.yml
Let's try to add caching to GitHub Actions in order to improve the reduce the memory usage
=> DX-1915 Add cache in GitHub Actions

_includes/instrument-mode.md
Removed some if's that did not work and cleared up some textual inconsistencies.
=> DX-1918: Instrument mode code example fixes

_includes/alert-balance-report-samples.md, _includes/alert-balance-report.md, _includes/settlement-reconciliation.md
Wrote two disclaimers and added them in the right sections.
=> DX-1922: Balance Report Disclaimers

payment-instruments/index.md
Removed Direct paragraph and fixed some forgotten headers.
=> DX-1923:  Remove link to Direct section from Payment Instruments intro

introduction.md
Rebase of PayEx/developer.swedbankpay.com#1.
=> Fixed typo in introduction.md

_includes/cross-channel-payments.md, checkout-v3/business/features/optional/cross-channel-payments.md, checkout-v3/enterprise/features/optional/cross-channel-payments.md, checkout-v3/payments-only/features/optional/cross-channel-payments.md, checkout-v3/starter/features/optional/cross-channel-payments.md
Tried adding a new icon and fixed a red code example
=> DX-1966: Reference Code cleanup

.github/workflows/azure-stage.yml
Fixes stage deploy by replacing the `azure/CLI` action with a regular `run` command.
=> DX-1977: Fix stage deploy

checkout-v3/business/seamless-view.md, checkout-v3/enterprise/seamless-view.md, checkout-v3/payments-only/seamless-view.md, checkout-v3/starter/seamless-view.md
Added -container to container names
=> DX-1956: Error in javascript example

.github/scripts/variables.sh, .github/workflows/azure-production.yml, .github/workflows/azure-stage.yml, .github/workflows/github-pages-production.yml, .github/workflows/github-pages-stage.yml, .github/workflows/test.yml, README.md, _includes/payment-order-afd.md, checkout-v3/business/features/optional/afd.md, checkout-v3/enterprise/features/optional/afd.md, checkout-v3/starter/features/optional/afd.md, gift-cards/test-client.md
Did some cosmetics and included it in all four implementations.
=> DX-1974: AFD cleanup

_includes/payment-order-age-restrictions.md, checkout-v3/business/features/optional/age-restrictions.md, checkout-v3/enterprise/features/optional/age-restrictions.md, checkout-v3/payments-only/features/optional/age-restrictions.md, checkout-v3/starter/features/optional/age-restrictions.md
Fixed some char pr line issues and some other cosmetics
=> DX-1984: Age Restriction Cosmetics

_includes/financing-consumer.md, payment-instruments/invoice/redirect.md
=> DX-1994: Invoice fixes

_includes/autoclick.md, _includes/checkout-v3-resource-models.md, _includes/payment-order-recur.md, _includes/payment-order-ssn-restrictions.md, _includes/payment-order-unscheduled.md, _includes/request-delivery-info.md, _includes/unscheduled-purchase.md, checkout-v3/enterprise/redirect.md, checkout-v3/enterprise/seamless-view.md, checkout-v3/payments-only/redirect.md, checkout-v3/payments-only/seamless-view.md, introduction.md
Searched and replaced node with field. Left the ones that was actual code or error messages generated elsewhere.
=> DX-2009: Replace node with field

_includes/settlement-reconciliation.md
=> DX-2022: Cleanup before 3.1.7

_includes/checkout-v3-resource-models.md, _includes/checkout-v3-status-models.md, _includes/instrument-mode.md, _includes/request-delivery-info.md, checkout-v3/payment-presentations.md
=> DX-2053: Added trademark icon to all mentions of Google Pay

_includes/one-click-payments.md
Finally fixed William's feedback
=> DX-1845: One Click Payments issues in payments only

resources/release-notes.md
Release notes 4.0.0
We promised you something big, and here it is. Click to Pay and Google Pay have been added to our arsenal of payment instruments. Click on your instrument of choice to read up on what is needed for you to activate in your integration. We have also added information on how to activate Apple Pay, which we recommend reading up on.
As you've probably already seen, our new sidebar is finally live too! We have given it a facelift and different levels which we hope make it easier for you to navigate. All the content is where it used to be. Check it out (and let us know what you think)! You might also wonder where the tables following our code examples have gone. We have made them expandable, and given them a facelift as well.
We have also added 3DS2 test data, along with …
=> Release 4.0.0 (develop)

_includes/recurring-card-payments.md
=> DX-2072: Small amount correction after feedback

checkout-v3/payment-presentations.md
Removed the faulty file. Rewrote text to prompt reader to copypaste our file instead.
=> Hotfix/dx 2090 fix apple pay domain file again (master)

index.md, partners.md, resources/partners.md
Added card for sales contact and partners. Also a landing page for the different countries' partners.
=> DX-2081: Added contact us and partners

_includes/payment-order-recur.md, _includes/payment-order-unscheduled.md, _includes/recurring-card-payments.md
Added info about capture and cancel to payment order recur and unscheduled
=> Hotfix DX-2098 add capture info to unscheduled and recur (master)

checkout-v3/resources/release-notes.md
Release notes 4.3.0
You spoke, we listened! We have worked a lot on making the portal easier to navigate. The main menu has been slimmed down, where we have removed the Introduction (but you can still read the main points under fundamental principles). If you are looking for the Resources and Modules & SDK sections, they have found a new home under Checkout v3.
Speaking of Checkout v3, we've cleaned that up as well, and hope it will make things easier for you. The request example now contains what you need to create a payment order. Adding more to it is up to you and the features section. The common implementations steps have been merged to avoid duplicate information, only sending you separate places when it's time to display the UI.
A new terminal section has been added. Exciting things …
=> Release 4.3.0 (develop)

old-implementations/payment-instruments-v1/index.md, old-implementations/payment-instruments-v1/invoice/direct.md, old-implementations/payment-instruments-v1/invoice/index.md, old-implementations/payment-instruments-v1/invoice/redirect.md, old-implementations/payment-instruments-v1/invoice/seamless-view.md
Rewrote disclaimer to state that invoice is no longer available in Sweden.
Removed Swedish and Finnish setup mail address.
Removed Swedish flag from payment instrument matrix.
=> DX-2143: Invoice payment instrument cleanup

checkout-v3/resources/release-notes.md
A small batch of changes which barely missed the last deadline. We've done a few correction and some major changes, most notably the renaming of **Checkout v3** to **Digital Payments** and **Pax Terminal** to **Payment Terminal**. The changes are in name only, the structure stays the same.
We have also added information regarding the Eligibility Check, and the availability of Invoice for **Swedish** merchants, where the payment instrument integrations have been removed. You have to go through an implementation using payment order to offer this in Sweden.
DX-2149: Even more links @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1890)
DX-2148: Fixed broken links in pax digital renaming @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pul …
=> Release 4.3.2 (develop)

_includes/payout.md
=> DX-2158: Payout PATCH

_includes/payout.md
=> DX-2162: Patch feedback

_includes/callback.md
Fixed some URLs and a text clarifying callback usage for payment order implementations
=> DX-2078: Callback improvements

pax-terminal/NET/Methods/paymentasync.md, pax-terminal/NET/Methods/start.md
Information about PaymentRequestResult updated
=> Dx 2169 update payment request async and its result as of terminal version 1 2 17

_includes/unscheduled-purchase-trustly.md
=> DX-2065: Update Trustly Unscheduled Disclaimer and callback info

_includes/fields/payee-reference.md
=> DX-2178: Fix payeeReference description

checkout-v3/features/optional/delete-token.md, old-implementations/checkout-v2/features/optional/delete-token.md, old-implementations/payment-menu-v2/features/optional/delete-token.md
Added payerownedtokens and changed content for v2 and payment menu
=> DX-2173: Add delete payerownedtokens to delete tokens

_includes/network-tokenization.md
Acquirer and Swedbank --> Swedbank Pay fixed.
=> DX-2185: Typos in NWT

_includes/delete-payment-order-token.md
Checking in to see if it's OK with William.
=> DX-2184: Adding TokenType to payerownedTokens

_includes/frictionless-payments.md, _includes/network-tokenization.md, _includes/transaction-list-response.md, checkout-v3/features/optional/delete-token.md, old-implementations/checkout-v2/features/optional/delete-token.md, old-implementations/payment-menu-v2/features/optional/delete-token.md
Fixed payerownedtokens, a table in frictionless payments and nwt example.
=> DX-2186: Last cleanups

checkout-v3/resources/release-notes.md
31 August 2023
Version 4.4.0
The wheels are picking up traction going into the autumn. Our first release after getting back is mostly maintenance and small fixes, but an important new addition is a section on Network Tokenization, which is a fantastic way of processing cards. Get to know it, and put it to use!
We have also adjusted our search results somewhat. Now we only display results from the sections Digital Payments and Payment Terminals. We hope it gives you an easier time finding the right result in the correct section.
Big things are coming up around the bend. Stay tuned!
Documentation
DX-2186: Last cleanups @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/1941)
DX-2171: Section names instead of implementations in urls @arebra …
=> Release 4.4.0 (develop)

_includes/custom-styling.md, checkout-v3/features/optional/custom-styling.md, checkout-v3/features/optional/delete-token.md, checkout-v3/features/optional/fees-discounts.md, checkout-v3/features/optional/instrument-mode.md, checkout-v3/features/optional/moto.md, checkout-v3/features/optional/network-tokenization.md, checkout-v3/features/optional/one-click-payments.md, checkout-v3/features/optional/order-items.md, checkout-v3/features/optional/payer-aware-payment-menu.md, checkout-v3/features/optional/payer-restrictions.md, checkout-v3/features/optional/payout.md, checkout-v3/features/optional/recur.md, checkout-v3/features/optional/request-delivery-info.md, checkout-v3/features/optional/split-settlement.md, checkout-v3/features/optional/tos.md, checkout-v3/features/optional/unscheduled.md, checkout-v3/features/optional/verify.md
First draft of custom styling and fixing the order of the optional features.
=> DX-2168: Custom styling

_includes/custom-styling.md
=> DX-2197: First adjustments Custom styling

_includes/custom-styling.md
Removed text about agreement and changed from bulletpoints to subheaders
=> DX-2203: Custom styling part 3

_includes/custom-styling.md, checkout-v3/display-payment-ui/index.md, checkout-v3/index.md, index.md
Removed a lot from the front page that is to be added to digital payments. Also rewrote intro to digpay.
Paid part is not complete!
=> DX-2183: Moving things from front page to digital payments part 1

checkout-v3/index.md, index.md
Moved cards back and did some text changes.
=> DX-2224: Move cards back to front page

checkout-v3/index.md, index.md
Added a sentence about the paid resource
=> DX-2215: Paid resource in digital payments text

checkout-v3/styling-info.md
Created a new page. Waiting on final copy.
=> DX-2230: Styling entry in DP menu

_includes/integrated-commerce.md, checkout-v3/features/optional/custom-logo.md, checkout-v3/features/optional/custom-styling.md, checkout-v3/features/optional/delete-token.md, checkout-v3/features/optional/fees-discounts.md, checkout-v3/features/optional/instrument-mode.md, checkout-v3/features/optional/integrated-commerce.md, checkout-v3/resources/release-notes.md, old-implementations/enterprise/features/optional/custom-logo.md, old-implementations/enterprise/features/optional/delete-token.md, old-implementations/enterprise/features/optional/enterprise-payer-reference.md, old-implementations/enterprise/features/optional/fees-discounts.md, old-implementations/enterprise/features/optional/instrument-mode.md, old-implementations/enterprise/features/optional/integrated-commerce.md, old-implementations/enterprise/features/optional/payout.md, old-implementations/enterprise/features/optional/recur.md, old-implementations/enterprise/features/optional/request-delivery-info.md, old-implementations/enterprise/features/optional/tos.md, old-implementations/enterprise/features/optional/tra.md, old-implementations/enterprise/features/optional/unscheduled.md, old-implementations/enterprise/features/optional/verify.md
Renamed section and re-arranged the menu accordingly
=> DX-2193: Rename Cross Channel Payments to Integrated Commerce

checkout-v3/resources/release-notes.md
If you are reading these notes, you have probably noticed some changes already! As the **Payment Terminals** section is growing bigger, we have moved most of the **Digital Payments** related content away from the front page. The release notes can now be found where you are reading this, and the resources at the bottom of the front page will follow suit shortly.
The biggest news is the arrival of the long-awaited Swedbank Pay Playground, where you can experience our payment solutions both as a payer and – since we give you access to the toolbox – a merchant. Play around with amounts, different menu setups (full menu, selected instruments or a single instrument) and styling. It is also a great opportunity to see the upcoming accessibility compliant UI, which is going live in October. With …
=> Release 4.5.0 (Develop)

pax-terminal/Nexo-Retailer/Quick-guide/eventnotifications.md, pax-terminal/Nexo-Retailer/Quick-guide/logout.md, pax-terminal/Nexo-Retailer/Quick-guide/messagetransportation.md, pax-terminal/Nexo-Retailer/Quick-guide/transactionstatus.md
added logout and event notification. Also corrected a dead link.
=> Dx 2194 reopened for correction and addition

checkout-v3/payment-presentations.md
=> DX-2188: Trustly Express

checkout-v3/index.md, checkout-v3/payment-presentations.md
Cosmetic touch ups of text and added a link in the payment instrument list
=> DX-2243: Trustly Express part 2

pax-terminal/index.md
fixed dead links om pax-terminal page
=> updated links

_includes/payment-order-3-1.md, _includes/payment-order-checkout-payments-only.md, _includes/payout.md
Fixed mandatory fields, added an indent or three, added company name.
=> DX-2253: Verify Trustly fixes

_includes/payout.md, checkout-v3/payment-presentations.md
Added two required check marks, made some changes to Trustly Express after Per's wishes and fixed some indents.
=> DX-2251: Trustly Express and Payout updates

_includes/payment-order-cancel-3-1.md, _includes/payment-order-cancel.md, _includes/payment-order-capture-3-1.md, _includes/payment-order-reversal-3-1.md, checkout-v3/index.md
=> DX-2255: Post-purchase 3.1 feedback

_includes/checkout-v3-resource-models.md, _includes/one-click-payments.md, checkout-v3/payment-request-3-1.md
Added a table to explain payerReference, fixed a typo and added a link.
=> DX-2258: Add one-click table

_includes/callback.md, _includes/checkout-v3-resource-models.md, checkout-v3/post-purchase-3-1.md, checkout-v3/post-purchase.md
Added number to callback and postpurchasefailedattempts. Also moved information regarding error messages in post-purchase.
=> DX-2270: Added number to callback and postpurchasefailedattempts

_includes/use-case-subscriptions.md, checkout-v3/features/index.md, checkout-v3/index.md, checkout-v3/migration-guide.md, checkout-v3/modules-sdks/index.md, checkout-v3/resources/index.md, checkout-v3/setup.md, checkout-v3/styling-info.md, checkout-v3/use-cases/index.md, checkout-v3/use-cases/subscriptions.md
and created links for both that and migration guide. Fixed menu order.
=> DX-2276: Added use case section

_includes/autoclick.md, _includes/callback.md, _includes/checkout-v2-resource-models.md, _includes/checkout-v2-status-models.md, _includes/checkout-v3-resource-models.md, _includes/checkout-v3-status-models.md, _includes/checkoutv3-purchase.md, _includes/instrument-mode.md, _includes/network-tokenization.md, _includes/payer-aware-payment-menu.md, _includes/payment-order-afd.md, _includes/payment-order-checkout-enterprise.md, _includes/payment-order-checkout-payments-only.md, _includes/payment-order-moto.md, _includes/payment-order-recur.md, _includes/payment-order-reversal.md, _includes/payment-order-unscheduled.md, _includes/request-delivery-info.md, _includes/status.md, _includes/tra.md, _includes/transaction-on-file.md, _includes/urls.md, _includes/verify.md, checkout-v3/features/core/cancel.md, checkout-v3/features/core/payment-order-capture.md, checkout-v3/features/core/reversal.md, checkout-v3/features/optional/one-click-payments.md, checkout-v3/modules-sdks/index.md, checkout-v3/resources/test-data.md
A bunch of small fixes, adding 3.1 to core features and adding a test section to network tokenization.
=> DX-2287: 3.1 in core features, network tokenization in test data and a heap of other fixes

checkout-v3/resources/release-notes.md
The last release of 2023 is finding its way down the chimney, and is mainly consisting of maintenance and small fixes.
There is however, one quite important update among all the small ones. We have added a test data section for Network Tokenization, with both test cards and other useful information. Head over to the Network Tokenization feature section if you want to learn more about what it is.
From all of us, to all of you: Merry Christmas!
DX-2297: Fixed more headers, removed an example and added a screenshot @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2056)
DX-2295: Pushing to stage for feedbacks sake. @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2055)
DX-2290: Draft of maskedpan and maskeddpan @arebra …
=> Release 4.6.1 (develop)

checkout-v3/test-data.md
Fixed redirect link and removed unused references.
=> Hotfix: DX-2358 Test Data Redirect link (Master)

_includes/problems/checkout.md
Added /paymentorders/ in urls where they were missing.
=> Hotfix: DX-2359 Token Inactive Url (Master)

_includes/problems/checkout.md
Added /paymentorders/ in the urls where they were missing.
=> Hotfix: DX-2359 Token Inactive Url (Develop)

_includes/payer-aware-payment-menu.md, _includes/problems/checkout.md, checkout-v3/test-data.md
=> DX-2240: Added new reattempts problems sections and new magic amounts

checkout-v3/release-notes.md
26 February 2024
Version 4.8.0
A handful of changes in the pipeline this time around, with the biggest being the introduction of better error codes for excessive re-attempts. Read all about the error codes and how to test them here.
Are you in the market for One-Click payments? We have a new use case written about that. Give it a read!
Due to new directives from card companies regarding frictionless payments, we have re-introduced name fields in the payer object. Go see the fields you should include now.
We have also added the possibility to display a consent box for saving payment details. When displayed by you and checked by the payer, we have also added a new field in the paid response, confirming that a token has been created.
Big changes are coming up next time. Stay tuned!
🖋 …
=> Release 4.8.0 (develop)

checkout-v3/get-started/index.md, checkout-v3/index.md
Added fancy "Why Swedbank Pay?" and fixed some headers
=> DX-343: Get Started feedback from Yvonne

checkout-v3/release-notes.md
Re-working of the Modules & SDKs section is the star of this release. Intrigued? Start off with the bare minimum implementation!
Aside from that, this has been a maintenance release, but the release notes you are reading right now received a facelift. We have also added more information about the final steps before you go live!
DX-367: Fixes of code tags @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2248)
DEVP-354: Changed illustration and capture text in get started @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2244)
DX-365: Removed a row and added a /div @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2243)
DEVP-364: Added card for one time usecase @arebra …
=> Release 5.1.0 (develop)

checkout-v3/features/index.md, checkout-v3/get-started/index.md, old-implementations/checkout-v2/features/optional/deposit-on-payment-button.md, old-implementations/checkout-v2/features/optional/fees-discounts.md, old-implementations/checkout-v2/features/optional/mac.md, old-implementations/checkout-v2/features/optional/recur.md, old-implementations/checkout-v2/features/optional/tra.md, old-implementations/checkout-v2/features/optional/unscheduled.md, old-implementations/checkout-v2/features/optional/verify.md, old-implementations/payment-menu-v2/features/optional/deposit-on-payment-button.md, old-implementations/payment-menu-v2/features/optional/fees-discounts.md, old-implementations/payment-menu-v2/features/optional/instrument-mode.md, old-implementations/payment-menu-v2/features/optional/moto.md, old-implementations/payment-menu-v2/features/optional/one-click-payments.md, old-implementations/payment-menu-v2/features/optional/payer-aware-payment-menu.md, old-implementations/payment-menu-v2/features/optional/payment-link.md, old-implementations/payment-menu-v2/features/optional/recur.md, old-implementations/payment-menu-v2/features/optional/transaction-on-file.md, old-implementations/payment-menu-v2/features/optional/unscheduled.md, old-implementations/payment-menu-v2/features/optional/verify.md
Also added deposit on payment button where it was lacking.
=> DX-389: Improvements on v3.x explanations

checkout-v3/release-notes.md
The keen eye might spot the new term v3.x in Get Started and some of our code examples. We are using it as an umbrella term whenever we talk about all iterations of v3. Instances where we talk about a specific one are still tagged with the version in question.
We are also going live with an optional feature called Action Specific Text On Payment Button. It is meant for scenarios where you need the payment button to say something else than "Pay". The alternative is currently limited to "Deposit", but other can be added going forward.
Besides that we have been doing some small bugfixes and general maintenance.
Until next time!
DEVP-387: Header cleanups part 2 @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2270)
DEVP-390: Renamed to Action Specific …
=> Release 5.2.0 (develop)

checkout-v3/release-notes.md
18 June 2024
Version 5.3.0
Our last release before the summer break is here, and we have quite the list of changes for you.
We have started restructuring the feature section to make it easier to navigate. A handful of new sections have been added, named Balancing The Books, Customize Payments and Customize The UI. Worried about your bookmarks? We've got you covered!
New error messages for invoice and installment account payments went live just now, and we have them at a plate for you. Just follow the respective links.
In all feature sections, the relevant field(s) have been moved to the top of of the code example.
Auto-expand first payment method has gotten it's own section.
Status and Status Response Models have been merged to one section.
We have added a new IP-address for callbacks. …
=> Release 5.3.0 (develop)

checkout-v3/release-notes.md
We are closing of August with a mellow, small release after being gone for summer, before gearing up for fall.
The Features restructuring continues with Core Features being renamed to Payment Operations, and moving Corporate Payment Menu to Customize the Payment UI.
We have added the recurring and one-click use cases to the sidebar for easier access.
As a part of our project to have error messages with better human readable information, the Excessive Reattempts responses for “Modifications required” and “Suspension Warning” got a facelift. The type and title field has been changed to authentication required, and the problem node has been replaced by a modification and suspension node respectively, filled with information directly from POS. 
The magic amount for triggering the …
=> Release 5.3.1 (develop)

checkout-v3/release-notes.md
24 October 2025
Version 5.3.2
Stricter PCI-CSS requirements are coming in the spring of 2025, and they could affect merchants using our Seamless View integration. We have addressed these changes and written a guide for transferring from Seamless View to the Redirect integration.
Not on our newest implementantion yet? There are guides for Payment Menu v2 and the Payment Methods which are inside the PCI-DSS zone available too. Information about Checkout v2 can be found here.
Version 5.0.0 of our Mobile SDK is also going live. The new additions are native payment features and a new automatic configuration feature introduced by the Session URL, making setup and usage simpler and quicker.
In that occasion, a new operation called view-paymentsession can be found in the payment order response, …
=> Release 5.3.2 (develop)

checkout-v3/apple-pay-presentation.md
Need linebreak in bullet points
=> DEVP-358: Re-arranged info and added points from Aman.

checkout-v3/release-notes.md
Version 5.3.4
A handful of small, but significant changes in the first update of 2025.
First of all, the Android and iOS SDKs have been promoted to supported status!
As the number of migration guides is going up, we have gathered them on a start page for accessability. In addition to the already existing “v2 to v3.1” and “Seamless View to Redirect” guides, a guide for going from Payment Methods v1 to Digital Payments v3.1 is now available.
New IP addresses for callbacks have been added in the callback section. They will be going live March 12th, so make sure you whitelist them as soon as possible.
While setting up a test account is free, making the switch to a production account isn’t, and it will generate a support fee for merchants who do this. Information about this has been added to …
=> Release 5.3.4 (develop)

checkout-v3/release-notes.md
A short and sweet one this time, with two important additions.
To help make the upcoming switch of IP addresses for callbacks as easy as possible, we have gathered your most likely questions in a FAQ section. Stop by to see if possible uncertainties have been addressed!
Pay SoftPos is going live this week, and that calls for a proper introduction. Head over to the brand new section to read about it!
DEVP-543: Fixed format of IP addresses @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2503)
DEVP-541: Fixed linebreaks and boldness @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2502)
DEVP-540: Header downgrade and text in disclaimer @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2500)
DEVP-534: Added FAQ …
=> Release 5.3.5 (develop)

404.md, Gemfile, Gemfile.lock, checkout-v3/modules-sdks/mobile-sdk/android.md, checkout-v3/modules-sdks/mobile-sdk/bare-minimum-implementation.md, checkout-v3/modules-sdks/mobile-sdk/ios.md
- Update to latest theme
- Use regular space instead of non-breakable space
=> Fix GitHub test errors

release-notes/digital-payments.md, release-notes/pay-softpos.md
Our release notes are on the move! We are taking steps towards a release notes hub for all sections, available straight from the main menu.
The biggest visual change this time around is a theme facelift with new cards. We have also and introduced tabs in sections where there are differences between versions - payment requests, post-purchase and callback.
SoftPos is also growing, and have added minimum device requirements, a list of proven/tested devices and the handful of unsupported ones.
Fixed release notes format, card and title @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2528)
Release notes fixes @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2527)
Develop pos @the-anders-jarold …
=> Release 5.3.6 (develop)

checkout-v3/apple-pay-presentation.md
And removed a right click + save as.
=> Re-arranged apple pay domain verification info

release-notes/digital-payments.md
A success always warrants a repeat, so a new FAQ section is going live today! This time we are addressing everything you need to know about E-Coms migration to Microsoft Azure.
We have also made some small additions to the Callback FAQ. Mainly clarifications about the grace period and whitelisting.
Added two callback FAQs @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2557)
Hotfix devp 579 hotfix of payeereference hotfix (develop-ecom) @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2556)
Hotfix devp-579 hotfix of payeereference hotfix (develop) @arebra (https://github.com/SwedbankPay/developer.swedbankpay.com/pull/2555)
Added missing string(30) on payeeReference (master) @arebra …
=> Release 5.3.7 (develop)

release-notes/digital-payments.md
13 August 2025
Documentation v5.3.9
We are getting things rolling again after the vacation weeks with a small and
sweet one. We are taking another step towards easier navigation by adding
payment method tags to features that are limited to certain methods.
Untagged features are universally available.
=> Release 5.3.10 (develop)
